# Factorización $LU$

Esta factorización consiste en determinar una forma equivalente para la matriz $A$ en la forma:


$$A = LU$$


Donde, $L$ es una matriz triangular inferior y $U$ es una matriz triangular superior, ahora bien, es importante señalar que no toda matriz no singular puede ser factorizada de esta forma, pero si una gran mayoría, por otra parte esta factorización nos beneficia al reducir el tiempo empleada en la solución del sistema.

## IPN, ESCOM
### Tarea 4, ejercicio 5.6
### Profesor: Israel Sánchez Mendoza, alumna: De Luna Ocampo Yanina
### Fecha de entrega: 29/11/2021

### Introducción
La factorización LU es una factorización que resume el proceso de eliminación gaussiana, se basa en separar una matriz A en dos matrices triangulares A = LU, donde L es una matriz triangular inferior y U (upper) es una matriz triangular superior, así, la resolución de estas dos subecuaciones es trivial.
En la lectura, primeramente consideraremos la factorización LU sin intercambio basada en matrices elementales y posteriormente da la factorización PA = LU.

### Proceso
Como siempre, debemos comenzar importando nuestras librerias necesarias, en este caso es para manipular arreglos y cosas necesarias de álgebra lineal, así como las funciones necesarias del determinante y para el método LU.

In [1]:
from numpy import array, zeros
import numpy as np

from numpy.linalg import det, solve, inv

from scipy.linalg import lu

Procedemos a definir la matriz con la que trabajaremos que es este caso es la siguiente:

In [2]:
A = array([[2, 1, 0, 0], [-1, 3, 3, 0], [2, -2, 1, 4], [-2, 2, 2, 5]], dtype = float)
B = array([[2, 1, 0, 0], [-1, 3, 3, 0], [2, -2, 1, 4], [-2, 2, 2, 5]], dtype = float)

Primero debemos validar que es una matriz invertible, de ahí calculamos el tamaño del sistema.
Construimos una matriz aumentada y asignamos los elementos de esta para determinar la factorización LU. Procedemos a identificar cómo se debe proceder para reducir la matriz para la siguiente fila tomando la fila para pivote de eliminación hacia abajo.
Debemos validar si el coeficiente de la línea pivote no es cero, luego si es diferente a cero y buscamos la celda que cumpla con esta última condición.
Imprimimos la matriz triangular inferior y el superior.

In [3]:
n = len(A)

if (det(A[:,:n]) != 0 and abs(det(A[:,:n])) > 10 ** (-5)):

    matrizA = np.zeros((n,2 * n))

    matrizA[:,0:n] = A.copy()
    matrizA[:,n:] = np.eye(n)
    
    print('La matriz aumentada con la que trabajaremos es: \n', matrizA, '\n')

    for j in range(n):

        pivote = matrizA[j,j]

        if pivote == 0:

            for k in range(j+1, n):

                if matrizA[k,j] != 0 :

                    cambio = matrizA[j,:].copy()

                    matrizA[j,:] = matrizA[k,:].copy()
                    matrizA[k,:] = cambio.copy()

                    break

        for i in range(j+1, n):

            coef = matrizA[i,j] / matrizA[j,j]

            matrizA[i,:] = matrizA[i,:] - coef * matrizA[j,:]
    
    # Imprimimos la matriz triangular inferior del proceso de eliminación
    print('La matriz L es: \n', matrizA[:,n:], '\n')
    
    # Imprimimos la matriz triangular superior
    print('La matriz U es: \n', matrizA[:,0:n], '\n')
    
else:
    
    print('La matriz no tiene solución única')

La matriz aumentada con la que trabajaremos es: 
 [[ 2.  1.  0.  0.  1.  0.  0.  0.]
 [-1.  3.  3.  0.  0.  1.  0.  0.]
 [ 2. -2.  1.  4.  0.  0.  1.  0.]
 [-2.  2.  2.  5.  0.  0.  0.  1.]] 

La matriz L es: 
 [[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [-0.57142857  0.85714286  1.          0.        ]
 [ 0.48       -0.72        0.16        1.        ]] 

La matriz U es: 
 [[2.         1.         0.         0.        ]
 [0.         3.5        3.         0.        ]
 [0.         0.         3.57142857 4.        ]
 [0.         0.         0.         5.64      ]] 



Validamos lo que el producto da como resultado.

In [4]:
inv(matrizA[:,n:]) @ matrizA[:,0:n]

array([[ 2.,  1.,  0.,  0.],
       [-1.,  3.,  3.,  0.],
       [ 2., -2.,  1.,  4.],
       [-2.,  2.,  2.,  5.]])

¿Qué aprendí con esta tarea?
Aprendimos de este método que es de gran utilidad ya que nos permite alivianar la cantidad de operaciones para resolver un sistema. Proporciona un medio eficiente para calcular matrices inversas y estas poseen un importante número de aplicaciones en la práctica de ingeniería. Este es un proceso abreviado, cuando programamos nos da ganancia.