# Método iterativo de Jacobi

El método de Jacobi se obtiene a partir de resolver la $i$ - ésima ecuación del sistema de ecuaciones $A\mathbf{x} = \mathbf{b}$ para la variable $x_{i}$, lo que resulta en (siempre y cuando $a_{ii}\neq 0$).


\begin{equation}
	\forall i=1,2,\dots,n\;\;\;\;x_{i}=\sum_{j=1;j\neq i}^{n}\left(-\frac{a_{ij}x_{j}}{a_{ii}}\right)+\frac{b_{i}}{a_{ii}}
\end{equation}


Posteriormente, para cada $k\geq 1$, se generan la siguientes componentes de $x_{i}^{(k)}$ del vector $\mathbf{x}^{(k)}$ a partir de los componentes de $\mathbf{x}^{(k-1)}$, siguiendo la siguiente fórmula:


\begin{equation}
    \forall i=1,2,\dots,n\;\;\;\;x_{i}^{(k)}=\frac{1}{a_{ii}}\sum_{j=1;j\neq i}^{n}\left(-a_{ij}x_{j}^{(k-1)}\right)+b_{i}
\end{equation}


El cual se puede ver en su forma matricial como:


\begin{equation}
    \mathbf{x}^{(k)}=A\mathbf{x}^{(k-1)}+\mathbf{b}
\end{equation}

### IPN, ESCOM
#### Tarea5, parcial3
#### Alumna: De Luna Ocampo Yanina, profesor: Israel Sánchez Mendoza
#### 01/12/2021

#### Introducción
Es un método iterativo usado para resolver sistemas de ecuaciones lineales del tipo. Este método consiste en usar fórmulas como iteración de punto fijo.
Un método iterativo con el cual se resuelve el sistema lineal A x = b, comienza con una aproximación inicial x (0) a la solución x y genera una sucesión de vectores x (k) que converge a x. Los métodos iterativos traen consigo un proceso que convierte el sistema A x = b en otro equivalente de la forma x = T x + c para alguna matriz fija T y un vector c.

#### Proceso
Como siempre, debemos empezar importando las librerías a utilizar que en este caso son para manipular arreglor y para álgebra lineal. Asimismo, las funciones para el determinante.

In [1]:
from numpy import array, zeros, eye
import numpy as np

from numpy.linalg import det, solve, inv

Empezamos definiendo los arreglos con los cuales vamos a trabajar en este problema.

In [2]:
A = array([[3, -1, 1], [3, 6, 2], [3, 3, 7]], dtype = float)
b = array([1, 0, 4], dtype = float)

Definimos nuestra aproximación inicial, la tolerancia de la misma, las máximas iteraciones y el contador que necesitaremos.

In [3]:
x = array([0, 0, 0], dtype = float)
tol = 10 ** (-6)
maxItera = 10
k = 0

Definimos la estandarización, dentro de esta la longitus y debemos proceder a normalizar la matriz. Definimos el método Jacobi, inicializamos el error y el contador. Imprimimos los resultados.

In [4]:
# Definimos la operación de la estandarización
def normal(A, b):
    
    # Determinamos la longitud de la matriz
    n = len(A)
    
    # Copia del arreglo
    Aestandar = A.copy()
    
    # Procedemos a normalizar la matriz
    for i in range(n):
        
        # Normalizamos el vector b
        b[i] = b[i] / A[i,i]
        
        # Normalizamos
        Aestandar[i] = Aestandar[i] / A[i,i]
        
        # Eliminamos el elemento de la diagonal
        Aestandar[i,i] = 0
        
    return -Aestandar, b

# Definimos el método de jacobi
def jacobi(A, b, x):
    
    # Calculamos el método
    jacobi = A@x + b
    
    return jacobi

# Definimos el proceso iterativo
def iterajacobi(A, b, x, tol, maxItera):
    
    # Inicializamos el error
    error = 100
    
    # Inicializamos el contador
    k = 0
    
    # iteramos el proceso
    while (error > tol and k < maxItera):
        
        # Actualizamos el contador
        k += 1
        
        # Actualizamos la aproximación
        x1 = jacobi(A, b, x)
        
        # Calculamos el error
        error = max(abs(x - x1))
        
        # Actualizamos
        x = x1
        
        # Imprimimos resultados
        print('Resultados de la iteracion: ', k)
        print('La aproximación de la solución se encuentra dada por:\n {}'.format(x))
        print('El error entre aproximaciones es de {}'.format(error))

In [5]:
A, b = normal(A, b)

Imprimimos los resultados para poder vusualizarlos de una mejor manera.

In [6]:
iterajacobi(A, b, x, tol, maxItera)

Resultados de la iteracion:  1
La aproximación de la solución se encuentra dada por:
 [0.33333333 0.         0.57142857]
El error entre aproximaciones es de 0.5714285714285714
Resultados de la iteracion:  2
La aproximación de la solución se encuentra dada por:
 [ 0.14285714 -0.35714286  0.42857143]
El error entre aproximaciones es de 0.3571428571428571
Resultados de la iteracion:  3
La aproximación de la solución se encuentra dada por:
 [ 0.07142857 -0.21428571  0.66326531]
El error entre aproximaciones es de 0.2346938775510204
Resultados de la iteracion:  4
La aproximación de la solución se encuentra dada por:
 [ 0.04081633 -0.25680272  0.63265306]
El error entre aproximaciones es de 0.04251700680272111
Resultados de la iteracion:  5
La aproximación de la solución se encuentra dada por:
 [ 0.03684807 -0.23129252  0.66399417]
El error entre aproximaciones es de 0.031341107871720175
Resultados de la iteracion:  6
La aproximación de la solución se encuentra dada por:
 [ 0.03490444 -0.239

¿Qué aprendí con esta tarea?
Partimos de una aproximación inicial para las soluciones al sistema de ecuaciones y sustituimos estos valores en la ecuación. De esta forma, se genera una nueva aproximación a la solución del sistema, que en determinadas condiciones, es mejor que la aproximación inicial. Esta nueva aproximación se puede sustituir de nuevo en la parte derecha de la ecuación y así sucesivamente hasta obtener la convergencia.