# Método iterativo de Jacobi

El método de Jacobi se obtiene a partir de resolver la $i$ - ésima ecuación del sistema de ecuaciones $A\mathbf{x} = \mathbf{b}$ para la variable $x_{i}$, lo que resulta en (siempre y cuando $a_{ii}\neq 0$).


\begin{equation}
	\forall i=1,2,\dots,n\;\;\;\;x_{i}=\sum_{j=1;j\neq i}^{n}\left(-\frac{a_{ij}x_{j}}{a_{ii}}\right)+\frac{b_{i}}{a_{ii}}
\end{equation}


Posteriormente, para cada $k\geq 1$, se generan la siguientes componentes de $x_{i}^{(k)}$ del vector $\mathbf{x}^{(k)}$ a partir de los componentes de $\mathbf{x}^{(k-1)}$, siguiendo la siguiente fórmula:


\begin{equation}
    \forall i=1,2,\dots,n\;\;\;\;x_{i}^{(k)}=\frac{1}{a_{ii}}\sum_{j=1;j\neq i}^{n}\left(-a_{ij}x_{j}^{(k-1)}\right)+b_{i}
\end{equation}


El cual se puede ver en su forma matricial como:


\begin{equation}
    \mathbf{x}^{(k)}=A\mathbf{x}^{(k-1)}+\mathbf{b}
\end{equation}

In [1]:
# Importamos la libreria de numpy para manipular arreglos y álgebra lineal
from numpy import array, zeros, eye
import numpy as np

# Importamos la función señalada del determinante
from numpy.linalg import det, solve, inv

In [2]:
# Definimos los arreglos con los cuales trabajaremos
A = array([[4, 1, -1, 1], [1, 4, -1, -1], [-1, -1, 5, 1], [1, -1, 1, 3]], dtype = float)
b = array([-2, -1, 0, 1], dtype = float)

In [3]:
# Definimos la aproximación inicial
x = array([0, 0, 0, 0], dtype = float)

# Tolerancia de la aproximación
tol = 10 ** (-6)

# Maximas iteraciones
maxItera = 100

# Contador
k = 0

In [4]:
# Definimos la operación de la estandarización
def normal(A, b):
    
    # Determinamos la longitud de la matriz
    n = len(A)
    
    # Copia del arreglo
    Aestandar = A.copy()
    
    # Procedemos a normalizar la matriz
    for i in range(n):
        
        # Normalizamos el vector b
        b[i] = b[i] / A[i,i]
        
        # Normalizamos
        Aestandar[i] = Aestandar[i] / A[i,i]
        
        # Eliminamos el elemento de la diagonal
        Aestandar[i,i] = 0
        
    return -Aestandar, b

# Definimos el método de jacobi
def jacobi(A, b, x):
    
    # Calculamos el método
    jacobi = A@x + b
    
    return jacobi

# Definimos el proceso iterativo
def iterajacobi(A, b, x, tol, maxItera):
    
    # Inicializamos el error
    error = 100
    
    # Inicializamos el contador
    k = 0
    
    # iteramos el proceso
    while (error > tol and k < maxItera):
        
        # Actualizamos el contador
        k += 1
        
        # Actualizamos la aproximación
        x1 = jacobi(A, b, x)
        
        # Calculamos el error
        error = max(abs(x - x1))
        
        # Actualizamos
        x = x1
        
        # Imprimimos resultados
        print('Resultados de la iteracion: ', k)
        print('La aproximación de la solución se encuentra dada por:\n {}'.format(x))
        print('El error entre aproximaciones es de {}'.format(error))

In [5]:
A, b = normal(A, b)

In [6]:
iterajacobi(A, b, x, tol, maxItera)

Resultados de la iteracion:  1
La aproximación de la solución se encuentra dada por:
 [-0.5        -0.25        0.          0.33333333]
El error entre aproximaciones es de 0.5
Resultados de la iteracion:  2
La aproximación de la solución se encuentra dada por:
 [-0.52083333 -0.04166667 -0.21666667  0.41666667]
El error entre aproximaciones es de 0.21666666666666667
Resultados de la iteracion:  3
La aproximación de la solución se encuentra dada por:
 [-0.64791667 -0.06979167 -0.19583333  0.56527778]
El error entre aproximaciones es de 0.14861111111111114
Resultados de la iteracion:  4
La aproximación de la solución se encuentra dada por:
 [-0.67282986  0.00434028 -0.25659722  0.59131944]
El error entre aproximaciones es de 0.07413194444444446
Resultados de la iteracion:  5
La aproximación de la solución se encuentra dada por:
 [-0.71306424  0.00188802 -0.25196181  0.64458912]
El error entre aproximaciones es de 0.05326967592592591
Resultados de la iteracion:  6
La aproximación de la sol